### ISSUE TITLE
Sum-product message passing marginal query run time 

### ISSUE THREAD

**Issue by tbenst** [ermongroup/cs228-notes#148]
The notes say this can be completed in constant time, but there are N(i)  multiplications, which would actually make it linear with respect to the degree of the vertex.

**Comment by raunakkmr** [comment]
Since the messages from node l to node i don't change once the BP algorithm terminates, you can precompute the product of messages from the neighbours of node i when you receive them during the BP algorithm. During inference, you can just look up this precomputed value rather than performing this product.

**Comment by tbenst** [comment]
Got it, thanks!
