### ISSUE TITLE
Discrepancy in front-end and back-end text for VE

### ISSUE THREAD

**Issue by Shushman** [ermongroup/cs228-notes#94]
If you look at the front end of the VE chapter under "An illustrative example" (as far as I can tell), you see in the first line "...simplicity that we a \n given a chain..."; but the text in the [source](https://github.com/ermongroup/cs228-notes/blob/master/inference/ve/index.md) clearly has "....we are given a chain....".

Is it just me or is there something going on here?

**Comment by chrisyeh96** [comment]
This was because the Markdown files get compiled into HTML for output. Previously, someone had to manually re-compile the HTML every time the Markdown files were changed, and it looks like someone forgot to do that. However, we have since changed this repo to automatically recompile, so this shouldn't be an issue anymore!
